-- $Id: gs.ads 78 2017-04-27 12:48:44Z jpuente $
--------------------------------------------------------------------------------
-- Project GS -- toy ground station
-- Main procedure specification
-- Copyright (c) 2017 Juan Antonio de la Puente <jpuente@dit.upm.es>
-- Permission to copy and modify are granted under the terms of
-- the GNU General Public License (GPL).
-- See http://www.gnu.org/licenses/licenses.html#GPL for the details
--------------------------------------------------------------------------------
-- usage:
-- gs [OBSW_IP [OBSW_Port [GS_TC_port]]]
procedure GS;
